#make_all.R
rm(list = ls())
cat("make_GISTIC1\n")
source("make_GISTIC1.R")
rm(list = ls())
cat("make_GISTIC2\n")
source("make_GISTIC2.R")
rm(list = ls())
cat("make_GEP\n")
source("make_GEP.R")
rm(list = ls())
cat("make_lymphoma2012\n")
source("make_lymphoma2012.R")
rm(list = ls())
cat("make_ricover\n")
source("make_ricover.R")
rm(list = ls())
cat("make_boxplot\n")
source("make_boxplot.R")
rm(list = ls())
cat("make_gistic2ge\n")
source("make_gistic2ge.R")
